ARG ELK_VERSION

FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

RUN kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistroAlertingKibana-1.13.0.0.zip